server.port=8080
massive.api.key=5A6b6w0TUby9q3TmDxfVkGr4MbLKVce8
spring.main.allow-bean-definition-overriding=true
# CORS configuration for local development
management.endpoints.web.exposure.include=*
